### ISSUE TITLE
Infinite stuck

### ISSUE THREAD

**Issue by Fonix420** [csharp-leaf/Leaf.xNet#83]
If you try to make any kind of request with a proxy which is also a url it will get stuck without crashing or ever moving forward

ex. 77.74.231.21:8028 which is also a site

**Comment by abhay991** [comment]
Hi, yes that is known issue in .net framework where it just doesn't timeout for some reason and idk if there is any solution to this but best alternative to this would be using httpclient and use wait method with timeout parameter.

**Comment by grandsilence** [comment]
Without a proxy, is the problem still showing up?

**Comment by grandsilence** [comment]
Is there a problem with .NET Core?

**Comment by Fonix420** [comment]
> 
> 
> Is there a problem with .NET Core?

Yes it is with .net core too, no only with this specific proxy(or any proxy which is also a url)

**Comment by grandsilence** [comment]
> > Is there a problem with .NET Core?
> 
> Yes it is with .net core too, no only with this specific proxy(or any proxy which is also a url)

@Fonix420 thank you for reporting. I'll try to fix that on the week.

**Comment by grandsilence** [comment]
Fixed by adding `UserAgent` header for `http://77.74.231.21:8028/`.

```csharp
            var req = new HttpRequest();
            req.UserAgent =
                "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.163 Safari/537.36";
            
            var resp = req.Get("http://77.74.231.21:8028/");
            string respStr = resp.ToString();
```

**Comment by Fonix420** [comment]
> 
> 
> Fixed by adding `UserAgent` header for `http://77.74.231.21:8028/`.
> 
> ```cs
> var req = new HttpRequest();
> req.UserAgent =
>     "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.163 Safari/537.36";
> 
> var resp = req.Get("http://77.74.231.21:8028/");
> string respStr = resp.ToString();
> ```
> 
> **More URLs needed for tests.**

Look at the image on the main post. The issue is send a request to that specific site while using the url as a proxy.

**Comment by Fonix420** [comment]
> 
> 
> Fixed by adding `UserAgent` header for `http://77.74.231.21:8028/`.
> 
> ```cs
> var req = new HttpRequest();
> req.UserAgent =
>     "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.163 Safari/537.36";
> 
> var resp = req.Get("http://77.74.231.21:8028/");
> string respStr = resp.ToString();
> ```
> 
> **More URLs needed for tests.**

`            HttpRequest cleint = new HttpRequest();
            var proxy = "77.74.231.21:8028";

            if (!string.IsNullOrEmpty(cleint.Get(proxy).ToString()))
            {
                Console.WriteLine("nigga is url");
                Console.ReadKey();
            }

            cleint.Proxy = HttpProxyClient.Parse(proxy);

            cleint.Cookies = new CookieStorage();
            cleint.Proxy.ConnectTimeout = 5000;
            cleint.Proxy.ReadWriteTimeout = 5000;
            cleint.ConnectTimeout = 5000;
            cleint.ReadWriteTimeout = 5000;
            cleint.KeepAliveTimeout = 5000;

            var html = cleint.Get("http://proxydb.net/anon");

            Console.WriteLine(html);

            Console.ReadKey();`

Try this code

**Comment by grandsilence** [comment]
Should be fixed in v5.2.9

**Comment by grandsilence** [comment]
@Fonix420 @abhay991 I need your feedback.

**Comment by Fonix420** [comment]
> 
> 
> @Fonix420 @abhay991 I need your feedback.

Im still having issues, same thing. It's just stuck on the get request

**Comment by grandsilence** [comment]
> > @Fonix420 @abhay991 I need your feedback.
> 
> Im still having issues, same thing. It's just stuck on the get request

It's stuck on `.Get()` call or on `.ToString()` call? Without proxy too?

**Comment by Fonix420** [comment]
> 
> 
> > > @Fonix420 @abhay991 I need your feedback.
> > 
> > 
> > Im still having issues, same thing. It's just stuck on the get request
> 
> It's stuck on `.Get()` call or on `.ToString()` call? Without proxy too?

On .Get(), only with this specific proxy on this specific site. All proxies which are also urls gets this issue on this url

**Comment by abhay991** [comment]
> @Fonix420 @abhay991 I need your feedback.

If i am not wrong i have faced this issue with webrequests in past as well. I have faced situation with (xNet) where it didn't timeout for actually hour as well. Also according to MSDN this might actually be an issue.

> A Domain Name System (DNS) query may take up to 15 seconds to return or time out. If your request contains a host name that requires resolution and you set Timeout to a value less than 15 seconds, it may take 15 seconds or more before a WebException is thrown to indicate a timeout on your request.

**Comment by grandsilence** [comment]
@Fonix420 Just tried to use `77.74.231.21:8028` proxy in Chrome, it's not working.
Also I've tried native`HttpClient`:  

```csharp
        private static void HttpClientTest()
        {
            var httpHandler = new HttpClientHandler {
                Proxy = new WebProxy("77.74.231.21:8028")
            };
            
            var httpClient = new HttpClient(httpHandler);
            httpClient.DefaultRequestHeaders.ExpectContinue = false;
            httpClient.DefaultRequestHeaders.UserAgent.TryParseAdd(
                "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.163 Safari/537.36"
            );

            var res = httpClient.GetStringAsync("http://proxydb.net/anon");
            var str = res.Result;
        }
        
```

`77.74.231.21:8028` is just not a correct proxy server I think.  
It's returning playlist stream instead of requested HTTP resource.
Without proxy or using correct proxy I haven't any issues on Net Framework 4.6.1.

**Comment by grandsilence** [comment]
Should be fixed in [v5.2.10](https://github.com/csharp-leaf/Leaf.xNet/releases/tag/v5.2.10) without side-effects.  
Any feedback?

**Comment by Fonix420** [comment]
> 
> 
> Should be fixed in [v5.2.10](https://github.com/csharp-leaf/Leaf.xNet/releases/tag/v5.2.10) without side-effects.
> Any feedback?

Same issue, try the exact code i sent before and you will see

**Comment by grandsilence** [comment]
> > Should be fixed in [v5.2.10](https://github.com/csharp-leaf/Leaf.xNet/releases/tag/v5.2.10) without side-effects.
> > Any feedback?
> 
> Same issue, try the exact code i sent before and you will see

Without proxy? `77.74.231.21:8028` is not a valid proxy. It's streaming server.

**Comment by Fonix420** [comment]
> 
> 
> > > Should be fixed in [v5.2.10](https://github.com/csharp-leaf/Leaf.xNet/releases/tag/v5.2.10) without side-effects.
> > > Any feedback?
> > 
> > 
> > Same issue, try the exact code i sent before and you will see
> 
> Without proxy? `77.74.231.21:8028` is not a valid proxy. It's streaming server.

With proxy, i need it to timeout in the case that i get another proxy like this when testing. I made a parser which checks proxies from a source and that is why i need it to timeout on these proxies instead of hanging.

**Comment by grandsilence** [comment]
@Fonix420 

> > > > Should be fixed in [v5.2.10](https://github.com/csharp-leaf/Leaf.xNet/releases/tag/v5.2.10) without side-effects.
> > > > Any feedback?
> > > 
> > > 
> > > Same issue, try the exact code i sent before and you will see
> > 
> > 
> > Without proxy? `77.74.231.21:8028` is not a valid proxy. It's streaming server.
> 
> With proxy, i need it to timeout in the case that i get another proxy like this when testing. I made a parser which checks proxies from a source and that is why i need it to timeout on these proxies instead of hanging.

Try using this proxy in any browser and you will realize that it does not work. To check the proxy, you must check the response from the proxy server and it must match the requested resource. What Timeout are you talking about if your proxy server is not a proxy server, but is streaming an infinite media stream.

**Comment by Fonix420** [comment]
> 
> 
> @Fonix420
> 
> > > > > Should be fixed in [v5.2.10](https://github.com/csharp-leaf/Leaf.xNet/releases/tag/v5.2.10) without side-effects.
> > > > > Any feedback?
> > > > 
> > > > 
> > > > Same issue, try the exact code i sent before and you will see
> > > 
> > > 
> > > Without proxy? `77.74.231.21:8028` is not a valid proxy. It's streaming server.
> > 
> > 
> > With proxy, i need it to timeout in the case that i get another proxy like this when testing. I made a parser which checks proxies from a source and that is why i need it to timeout on these proxies instead of hanging.
> 
> Try using this proxy in any browser and you will realize that it doesn't work. To check the proxy, you must check the response from the proxy server and it must match the requested resource. What Timeout are you talking about if your proxy server is not a proxy server, but is streaming an infinite media stream.

Yes i know but my tool looks for random proxies on sources and then tests them. So once it finds a proxy like this and tries to test it, it gets stuck. I need it to throw an exception or timeout.

**Comment by grandsilence** [comment]
@Fonix420 Now I get it, thanks for the explanation. Will be fixed soon.

**Comment by Fonix420** [comment]
> 
> 
> @Fonix420 Now I get it, thanks for the explanation. Will be fixed soon.

Thanks, sorry for not explaining it better from the beginning.

**Comment by uahmad235** [comment]
I am also facing the same issue. Getting stuck forever on the Http GET method. POST works fine for me.
It is happening only in the case of **HttpProxyClient.Parse** and working fine for Other proxy types e.g., Socks5ProxyClient and Socks5ProxyClient.

**Comment by CripWalked** [comment]
you guys didnt set the proxy type when setting the proxy...
`                        
httpRequest.Proxy = ProxyClient.Parse(ProxyType.HTTP, proxy);
`
if this doesnt work, try using TRY & catch before requesting anything.
`
 using (HttpRequest httpRequest = new HttpRequest())
 {
       try {
       //request code here.
       }
       catch {
       }
 }
`

**Comment by D1og0** [comment]
> you guys didnt set the proxy type when setting the proxy... ` httpRequest.Proxy = ProxyClient.Parse(ProxyType.HTTP, proxy);` if this doesnt work, try using TRY & catch before requesting anything. `using (HttpRequest httpRequest = new HttpRequest()) { try { //request code here. } catch { } }`

Not working...

**Comment by CripWalked** [comment]
> > you guys didnt set the proxy type when setting the proxy... ` httpRequest.Proxy = ProxyClient.Parse(ProxyType.HTTP, proxy);` if this doesnt work, try using TRY & catch before requesting anything. `using (HttpRequest httpRequest = new HttpRequest()) { try { //request code here. } catch { } }`
> 
> Not working...

you probally did it wrong then, cant help

**Comment by D1og0** [comment]
> > > you guys didnt set the proxy type when setting the proxy... ` httpRequest.Proxy = ProxyClient.Parse(ProxyType.HTTP, proxy);` if this doesnt work, try using TRY & catch before requesting anything. `using (HttpRequest httpRequest = new HttpRequest()) { try { //request code here. } catch { } }`
> > 
> > 
> > Not working...
> 
> you probally did it wrong then, cant help

I switched to xNet and now is working lmao

**Comment by novacisadev** [comment]
I have an issue where it just wont return the response data, like it connects and does all the right things, but when I try to turn it into a string it sits for about 30 sec and returns this error:

`IOException: Unable to read data from the transport connection: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond..`

`SocketException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.`
